### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by juaningan** [t0mk/kraken-python3-cli#1]
Hi, I don't very sure if you want to output JSON for command. But if it is correct I think that you have to use double quotes. Some programs like 'jq' don't like single quotes and are not compliant with JSON standard:  For reference: http://api.jquery.com/jQuery.parseJSON/ or https://stackoverflow.com/questions/14355655/jquery-parsejson-single-quote-vs-double-quote

Thanks for your work.

**Comment by t0mk** [comment]
Hi @juaningan, thanks for using kraken-python3-cli.

It's not my goal to output JSON with this tool. The goal is to have a usable CLI for Kraken.

The "json()" calls in the code are actually calls to a method of HTTP Response object from Python Requests. It doesn't _return_ json, but rather it loads json from the body of the request into python structure (dict/list/string). So whatever the tool prints is not supposed to be json, but just Python structures.

The code of the json() from Requests is, I believe, this:
http://docs.python-requests.org/en/master/_modules/requests/models/#Response.json

If you want to call Kraken API from Javascript, I would recommend something like this:
http://docs.python-requests.org/en/master/_modules/requests/models/#Response.json

If you want JSON
