### ISSUE TITLE
JSON Decoder Error

### ISSUE THREAD

**Issue by pedrosimao** [t0mk/kraken-python3-cli#2]
Every time I try to pass a command like "./kx Balance" or "./kx TradeBalance EUR" i get this error: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by pedrosimao** [comment]
I am also getting invalid nonce errors:
Exception: EAPI:Invalid nonce

**Comment by t0mk** [comment]
Hi, I haven't had time to touch this project for a long time. You cna see what it sends and recevies when you set envvar DEBUG to nonempty string, e.g.
DEBUG=1 ./kx Balance

I am open to pull requests, for example listing new currencies, pairs, etc.

**Comment by t0mk** [comment]
But thanks for you submission, it's good to know about issues :)

**Comment by t0mk** [comment]
@pedrosimao I was fixing another issue, and decided to test this too.

I set up my 2FA and API keys, and I verified that both Balance and TradeBalance work fine for me.

Please check your auth, or submit HTTP request and response of the err behavior.

**Comment by pedrosimao** [comment]
@t0mk , I haven't tried to use your app since December. So I don't even remember exactly what I was doing. I think there is a high probability that the problem came from Kraken itself, as at the time their entire website was buggy, and I was trying to use the CLI to see if I could move some funds without using the website. It happens that their API was bugging too...

**Comment by t0mk** [comment]
@pedrosimao, never mind then, and thanks anyway. Withdrawal is really painful through Kraken web. IIRC it's several clicks over long page loads. It's a good point that this tool could make it easier to do the withdrawals. If I find the time, I will put a short withdrawal howto to the README of this repo.
