### ISSUE TITLE
XRPUSD missing 

### ISSUE THREAD

**Issue by maskedstatistician** [t0mk/kraken-python3-cli#5]
Hi,

It seems we are missing XRPUSD on the AddOrder possibilities

```
./kx AddOrder -p 9900 XXRPZUSD buy stop-loss 10

error: argument pair: invalid choice: 'XXRPZUSD'
```

We do have it on the assets as 
```
./kx AssetPairs | grep XXRPZUSD
ZUSD                    1  unit                 5  XRPUSD                40  []                         80  XXRPZUSD    []               XXRP
```

Best,

**Comment by t0mk** [comment]
Hi @maskedstatistician thanks for the report. I updated the list of assets and pairs from latest API listing, it should work now.

**Comment by maskedstatistician** [comment]
Hi,

Thanks for your reactivity ! Yes I confirm it is now working perfectly.
